SELECT DISTINCT CITY
  FROM STATION
  WHERE CITY LIKE 'A%'
     OR CITY LIKE 'E%'
     OR CITY LIKE 'I%'
     OR CITY LIKE 'O%'
     OR CITY LIKE 'U%';
    
--정규표현식을 이용하면
SELECT DISTINCT CITY
  FROM STATION
  WHERE REGEXP_LIKE(CITY, '^A|^E|^I|^O|^U');

SELECT DISTINCT CITY
  FROM STATION
  WHERE REGEXP_LIKE(CITY, '^[AEIOU]');
